const FIVE_MINUTES_IN_SECONDS = 300;
const SIXTY_MINUTES_IN_SECONDS = 3600;
const THIRTY_MINUTES = "30m";
const THIRTY_MINUTES_IN_SECONDS = 1800;

module.exports = {
    FIVE_MINUTES_IN_SECONDS,
    SIXTY_MINUTES_IN_SECONDS,
    THIRTY_MINUTES,
    THIRTY_MINUTES_IN_SECONDS,
};